name: Updating GTN tools

on:
  schedule:
    # Runs weekly, every Saturday at 02:00 UTC (alligned with off-peak hours)
    - cron: "0 2 * * SAT"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install ephemeris
      - name: Clone GTN repository
        uses: actions/checkout@v4
        with:
          repository: galaxyproject/training-material
          path: training-material
          ref: main
      - name: Run updater script
        run: python3 scripts/gtn-tools-updater.py ${GITHUB_WORKSPACE}/training-material/ ${GITHUB_WORKSPACE}/GTN_tutorials_tools.yaml ${GITHUB_WORKSPACE}/tools_iuc.yaml.lock ${GITHUB_WORKSPACE}/section_mapping.yml
      - name: Deleting GTN repository
        run: rm -r training-material
      - name: Show differences
        run: "git diff --stat"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update GTN workflows
          title: "Automatic updating of the GTN tools"
          body: |
            This PR is automatically generated based on changes in the [Galaxy Training Network](https://github.com/galaxyproject/training-material) workflows.

            Please verify if these changes are valid.
          labels: |
            automatic PR
          branch: gtn-update
          base: master

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
